import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navigation from "@/app/components/Navigation"; // Import the Navigation component
import { CopilotKit } from "@copilotkit/react-core"; // Import CopilotKit component

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "X Post Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CopilotKit publicApiKey={process.env.NEXT_PUBLIC_COPILOTKIT_API_KEY}>
          <Navigation /> {/* Added the Navigation component here */}
          <main className="container mx-auto mt-8">
            {children}
          </main>
        </CopilotKit>
      </body>
    </html>
  );
}
